IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[WSP_RESTOREDB]') AND type in (N'P', N'PC'))
BEGIN
	DROP PROCEDURE [dbo].[WSP_RESTOREDB];
END
GO


/*
exec WSP_RESTOREDB 
@RESTOREDB='V@LID49V4_2009_CRB',
@BACKUPDB='F:\SVN_Ibmserver\REGIONAL III\Kab. Cirebon\DataBase\V@LID49V4_2009_CRB',
@MDFLDFPATH = 'E:\MSSQL2008\Data\DBI'
--*/

CREATE PROCEDURE [dbo].[WSP_RESTOREDB] 
(@RESTOREDB varchar(300), @BACKUPDB varchar(300), @MDFLDFPATH VARCHAR(300),@DATAFILE VARCHAR(300),@BAKFILE VARCHAR(300) )
AS
DECLARE @LOKASI_MDF VARCHAR(300)
IF @MDFLDFPATH IS NULL OR @MDFLDFPATH = ''
BEGIN
	SET @LOKASI_MDF = 'D:\MSSQL2005\DATA\'
END
ELSE
BEGIN
	SET @LOKASI_MDF = @MDFLDFPATH	
END
IF RIGHT(RTRIM(@LOKASI_MDF),1) <> '\'
BEGIN
	SET @LOKASI_MDF = RTRIM(@LOKASI_MDF) + '\'
END

--/*
DECLARE @CONN_COUNT INT, @KILLID SMALLINT, @STRKILL NVARCHAR(255)
SET @CONN_COUNT = ISNULL((SELECT COUNT(*) FROM [master].dbo.SYSPROCESSES S INNER JOIN SYS.databases d ON D.database_id = S.dbid WHERE d.[name] = @RESTOREDB AND S.SPID <> @@SPID),0)	
WHILE @CONN_COUNT > 0
BEGIN
	SET @KILLID = (SELECT TOP 1 S.spid FROM [master].dbo.SYSPROCESSES S INNER JOIN SYS.databases d ON D.database_id = S.dbid WHERE d.[name] = @RESTOREDB AND S.SPID <> @@SPID)
	IF @KILLID IS NOT NULL 
	BEGIN
		SET @STRKILL = 'KILL ' + CAST(@KILLID AS CHAR(3))
		EXECUTE sp_executesql @STRKILL	
	END			
	SET @CONN_COUNT  = ISNULL((SELECT COUNT(@KILLID)),0)
END
--*/

DECLARE @SQLRESTORE NVARCHAR(1000)
SET @SQLRESTORE = '
RESTORE DATABASE ' + @RESTOREDB + '
FROM DISK = ''' + @BACKUPDB + ''' WITH REPLACE, 
MOVE '''+@DATAFILE+''' TO ''' + @LOKASI_MDF + '' + @RESTOREDB + '.MDF'', 
MOVE '''+@BAKFILE+''' TO ''' + @LOKASI_MDF + '' + @RESTOREDB + '.LDF'''
EXECUTE sp_executesql @SQLRESTORE 

GO

