USE [V@LID49ASETV5]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] DROP CONSTRAINT [FK_ASET_HAPUSSK_JTRANS]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] DROP CONSTRAINT [FK_ASET_HAPUSSK_DAFTUNIT]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] DROP CONSTRAINT [DF__ASET_HAPU__DATEU__7B9B496D]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] DROP CONSTRAINT [DF__ASET_HAPU__DATEC__7AA72534]
GO

/****** Object:  Table [dbo].[ASET_HAPUSSK]    Script Date: 28/09/2022 03:46:17 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ASET_HAPUSSK]') AND type in (N'U'))
DROP TABLE [dbo].[ASET_HAPUSSK]
GO

/****** Object:  Table [dbo].[ASET_HAPUSSK]    Script Date: 28/09/2022 03:46:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ASET_HAPUSSK](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UNITKEY] [nchar](36) NOT NULL,
	[NOSKHAPUS] [nvarchar](50) NOT NULL,
	[TGLSKHAPUS] [datetime] NOT NULL,
	[KET] [nvarchar](4000) NULL,
	[TGLVALID] [datetime] NULL,
	[DATECREATE] [datetime] NULL,
	[DATEUPDATE] [datetime] NULL,
	[KDTANS] [nchar](3) NULL,
 CONSTRAINT [PK_ASET_HAPUSSK] PRIMARY KEY CLUSTERED 
(
	[UNITKEY] ASC,
	[NOSKHAPUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] ADD  CONSTRAINT [DF__ASET_HAPU__DATEC__7AA72534]  DEFAULT (getdate()) FOR [DATECREATE]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] ADD  CONSTRAINT [DF__ASET_HAPU__DATEU__7B9B496D]  DEFAULT (getdate()) FOR [DATEUPDATE]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK]  WITH CHECK ADD  CONSTRAINT [FK_ASET_HAPUSSK_DAFTUNIT] FOREIGN KEY([UNITKEY])
REFERENCES [dbo].[DAFTUNIT] ([UNITKEY])
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] CHECK CONSTRAINT [FK_ASET_HAPUSSK_DAFTUNIT]
GO

ALTER TABLE [dbo].[ASET_HAPUSSK]  WITH CHECK ADD  CONSTRAINT [FK_ASET_HAPUSSK_JTRANS] FOREIGN KEY([KDTANS])
REFERENCES [dbo].[JTRANS] ([KDTANS])
GO

ALTER TABLE [dbo].[ASET_HAPUSSK] CHECK CONSTRAINT [FK_ASET_HAPUSSK_JTRANS]
GO


