/****** Object:  Table [dbo].[EVENT]    Script Date: 26/08/2022 08:12:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVENT](
	[IDLOG] [uniqueidentifier] NOT NULL,
	[USERID] [nvarchar](64) NULL,
	[TGLLOG] [datetime] NOT NULL,
	[COMPUTER_NAME] [nvarchar](50) NULL,
	[COMPUTER_IP] [nvarchar](50) NULL,
	[APP_NAME] [nvarchar](50) NULL,
	[USER_DB] [nvarchar](64) NULL,
	[USER_APP] [nvarchar](64) NULL,
	[USER_MENU] [nvarchar](64) NULL,
	[KDTYPE] [nchar](64) NOT NULL,
	[STATUS] [int] NULL,
	[LOGDATA] [ntext] NULL,
 CONSTRAINT [PK_EVENT] PRIMARY KEY CLUSTERED 
(
	[IDLOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EVENTTYPES]    Script Date: 26/08/2022 08:12:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVENTTYPES](
	[KDTYPE] [nchar](30) NOT NULL,
	[NMTYPE] [nvarchar](128) NULL,
	[KDLEVEL] [smallint] NULL,
	[TYPE] [nchar](1) NULL,
	[NOTES] [ntext] NULL,
	[LAST_BY] [nvarchar](64) NULL,
	[LAST_DATE] [datetime] NULL,
 CONSTRAINT [PK_LOGTypes] PRIMARY KEY CLUSTERED 
(
	[KDTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTES]    Script Date: 26/08/2022 08:12:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTES](
	[IDNOTES] [nchar](36) NOT NULL,
	[TGLNOTES] [datetime] NULL,
	[REFDB] [nvarchar](64) NULL,
	[REFTABEL] [nvarchar](64) NULL,
	[REFID] [nvarchar](128) NULL,
	[NOTESTYPE] [int] NULL,
	[NOTES] [ntext] NULL,
	[STATUS] [int] NULL,
	[LAST_BY] [nvarchar](64) NULL,
	[LAST_DATE] [datetime] NULL,
 CONSTRAINT [PK_LOGNotes] PRIMARY KEY CLUSTERED 
(
	[IDNOTES] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTESTYPES]    Script Date: 26/08/2022 08:12:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTESTYPES](
	[NOTESTYPE] [int] NULL,
	[DESC] [nvarchar](128) NULL
) ON [PRIMARY]
GO
