
GO

/****** Object:  StoredProcedure [dbo].[WSPX_REKLASLAIN2]    Script Date: 01/11/2023 08:39:08 ******/
DROP PROCEDURE [dbo].[WSPX_REKLASLAIN2]
GO

/****** Object:  StoredProcedure [dbo].[WSPX_REKLASLAIN2]    Script Date: 01/11/2023 08:39:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[WSPX_REKLASLAIN2]
(@UNITKEY CHAR(36), @NOREKLAS CHAR(50), @TGLREKLAS DATETIME, @KDTANS CHAR(3))
AS



--DECLARE @UNITKEY CHAR(36), @NOREKLAS CHAR(50), @TGLREKLAS DATETIME, @KDTANS CHAR(3)
--SET @UNITKEY = '345_'
--SET @NOREKLAS = '0002-asetlainnya'
--SET @TGLREKLAS = '2022-10-31'
--SET @KDTANS = '233'

--IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#KIB_REKLAS%')
--   DROP TABLE #KIB_REKLAS


SELECT IDENTITY(INT,1,1) NOURUT, A.UNITKEY, A.NOREKLAS, AR.TGLREKLAS, A.KDTANS, AR.KET AS URAITRANS, YEAR(AR.TGLREKLAS) AS THANG, A.ASETKEY, D.KDASET, D.UMEKO, J.KDKIB, 
A.ASETKEY2, DA.KDASET AS KDASET_2, DA.UMEKO AS UMEKO_2, JA.KDKIB AS KDKIB_2, A.TAHUN, A.NOREG, A.IDBRG, A.KDKON, A.NILAI
INTO #KIB_REKLAS
FROM ASET_REKLASDET A
LEFT JOIN ASET_REKLAS AR ON AR.UNITKEY = A.UNITKEY AND AR.NOREKLAS = A.NOREKLAS AND AR.KDTANS = A.KDTANS
LEFT JOIN DAFTASET D ON D.ASETKEY = A.ASETKEY
LEFT JOIN JNSKIBASET J ON J.K_BRG = LEFT(D.KDASET,9)
LEFT JOIN DAFTASET DA ON DA.ASETKEY = A.ASETKEY2
LEFT JOIN JNSKIBASET JA ON JA.K_BRG = LEFT(DA.KDASET,9)
WHERE A.UNITKEY=@UNITKEY AND A.NOREKLAS=@NOREKLAS AND A.KDTANS=@KDTANS



SET XACT_ABORT ON
BEGIN TRANSACTION

DECLARE @NROW AS INT, @I INT, @MAXURUTTRANS INT, @NOREGN VARCHAR(10), @KDKIB CHAR(2), @KDKIB_2 CHAR(2), @IDBRG CHAR(10)
	
SET @NROW = (SELECT MAX(NOURUT) FROM #KIB_REKLAS)
SET @I = 1

WHILE @I <= @NROW
BEGIN
	SET @KDKIB			= (SELECT K.KDKIB FROM #KIB_REKLAS K WHERE K.NOURUT = @I)
	SET @KDKIB_2		= (SELECT K.KDKIB_2 FROM #KIB_REKLAS K WHERE K.NOURUT = @I)
	SET @IDBRG			= (SELECT K.IDBRG FROM #KIB_REKLAS K WHERE K.NOURUT = @I)
	SET @MAXURUTTRANS	= (SELECT MAX(CAST(X.URUTTRANS AS INT)) FROM (
							SELECT URUTTRANS FROM ASET_KIBADET WHERE IDBRG=@IDBRG UNION ALL
							SELECT URUTTRANS FROM ASET_KIBBDET WHERE IDBRG=@IDBRG UNION ALL
							SELECT URUTTRANS FROM ASET_KIBCDET WHERE IDBRG=@IDBRG UNION ALL
							SELECT URUTTRANS FROM ASET_KIBDDET WHERE IDBRG=@IDBRG UNION ALL
							SELECT URUTTRANS FROM ASET_KIBEDET WHERE IDBRG=@IDBRG UNION ALL
							SELECT URUTTRANS FROM ASET_KIBGDET WHERE IDBRG=@IDBRG) X)
							   
	IF (@KDKIB = '01')
	BEGIN
		/* INSERT REKLAS KELUAR */ 
		SELECT K.IDBRG, K.UNITKEY, K.ASETKEY, K.KDASET, K.TAHUN, K.NOREG, K.NOREKLAS, K.TGLREKLAS, K.NILAI, K.UMEKO, K.KDKIB, K.URAITRANS, 
		A.KDKON, A.KDKLAS, A.KDSENSUS, A.KDSTATUSASET, A.KDLOKPO, A.KDBRGPO, K.THANG, K.ASETKEY2, K.KDASET_2, K.UMEKO_2, K.KDKIB_2
		INTO #REKLAS_KIBA
		FROM #KIB_REKLAS K
		INNER JOIN ASET_KIBADET A ON A.IDBRG = K.IDBRG AND A.URUTTRANS = @MAXURUTTRANS
		WHERE K.NOURUT = @I
			
		INSERT INTO ASET_KIBADET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
		SELECT IDBRG, @MAXURUTTRANS+1, UNITKEY, ASETKEY, TAHUN, NOREG, @KDTANS, NOREKLAS, TGLREKLAS, NILAI, UMEKO, KDKIB, URAITRANS, 
		KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDBRGPO, THANG
		FROM #REKLAS_KIBA
		
		/* REKLAS ASET TETAP INSERT REKLAS MASUK -- PEMILIHAN KIB TUJUAN */	
		IF (@KDTANS = '233') 
		BEGIN
			IF (@KDKIB_2 = '08')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBADET A
								INNER JOIN #REKLAS_KIBA K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBADET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBA K
			END
			ELSE IF (@KDKIB_2 = '09')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBADET A
								INNER JOIN #REKLAS_KIBA K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBADET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, '09' KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBA K
			END
			
			/* INSERT KIB_SPESIFIKASI */ 
			INSERT INTO ASET_KIBSPESIFIKASI(IDBRG,URUTHIST,UNITKEY,ASETKEY,TAHUN,NOREG,KDKIB,KDPEMILIK,ASALUSUL,PENGGUNA,KET,KDHAK,LUASTNH,ALAMAT,NOFIKAT,TGFIKAT,KDSATUAN,MERKTYPE,UKURAN,
			BAHAN,KDWARNA,NOPABRIK,NORANGKA,NOPOLISI,NOBPKB,NOMESIN,BERTINGKAT,BETON,LUASLT,NODOKGDG,TGDOKGDG,KONSTRUKSI,PANJANG,LEBAR,LUAS,NODOKJIJ,TGDOKJIJ,JDLPENERBIT,BKPENCIPTA,SPESIFIKASI,
			ASALDAERAH,PENCIPTA,JENIS,KDFISIK,NODOKKDP,TGDOKKDP,TGMULAI,NOKDTANAH,JUDUL)
			SELECT AK.IDBRG, @MAXURUTTRANS+2, AK.UNITKEY, K.ASETKEY2, K.TAHUN, @NOREGN, K.KDKIB_2, AK.KDPEMILIK, AK.ASALUSUL, AK.PENGGUNA, AK.KET, AK.KDHAK,AK.LUASTNH, AK.ALAMAT, AK.NOFIKAT, 
			AK.TGFIKAT, AK.KDSATUAN,AK.MERKTYPE, AK.UKURAN, AK.BAHAN, AK.KDWARNA, AK.NOPABRIK,AK.NORANGKA, AK.NOPOLISI, AK.NOBPKB, AK.NOMESIN, AK.BERTINGKAT,AK.BETON, AK.LUASLT, AK.NODOKGDG, 
			AK.TGDOKGDG, AK.KONSTRUKSI,	AK.PANJANG, AK.LEBAR, AK.LUAS, AK.NODOKJIJ, AK.TGDOKJIJ,AK.JDLPENERBIT, AK.BKPENCIPTA, AK.SPESIFIKASI, AK.ASALDAERAH,AK.PENCIPTA, AK.JENIS, AK.KDFISIK, 
			AK.NODOKKDP, AK.TGDOKKDP, AK.TGMULAI, AK.NOKDTANAH, AK.JUDUL
			FROM #REKLAS_KIBA K
			INNER JOIN ASET_KIBSPESIFIKASI AK ON AK.IDBRG = K.IDBRG AND AK.UNITKEY = K.UNITKEY AND AK.ASETKEY = K.ASETKEY
		END
			
		/* UPDATE STATUS REKLAS */ 
		UPDATE ASET_REKLASDET
		SET NOREG2 = (CASE WHEN @KDTANS = '233' THEN @NOREGN ELSE ''END), [STATUS] = '1'
		FROM ASET_REKLASDET A
		INNER JOIN #REKLAS_KIBA R ON R.UNITKEY = A.UNITKEY AND R.NOREKLAS = A.NOREKLAS AND A.KDTANS = @KDTANS AND R.ASETKEY = A.ASETKEY AND R.TAHUN = A.TAHUN AND R.IDBRG = A.IDBRG
			
		IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#REKLAS_KIBA%')
		DROP TABLE #REKLAS_KIBA
	END
	ELSE IF (@KDKIB = '02')
	BEGIN
		/* INSERT REKLAS KELUAR */ 
		SELECT K.IDBRG, K.UNITKEY, K.ASETKEY, K.KDASET, K.TAHUN, K.NOREG, K.NOREKLAS, K.TGLREKLAS, K.NILAI, K.UMEKO, K.KDKIB, K.URAITRANS, 
		A.KDKON, A.KDKLAS, A.KDSENSUS, A.KDSTATUSASET, A.KDLOKPO, A.KDBRGPO, K.THANG, K.ASETKEY2, K.KDASET_2, K.UMEKO_2, K.KDKIB_2
		INTO #REKLAS_KIBB
		FROM #KIB_REKLAS K
		INNER JOIN ASET_KIBBDET A ON A.IDBRG = K.IDBRG AND A.URUTTRANS = @MAXURUTTRANS
		WHERE K.NOURUT = @I
			
		INSERT INTO ASET_KIBBDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
		SELECT IDBRG, @MAXURUTTRANS+1, UNITKEY, ASETKEY, TAHUN, NOREG, @KDTANS, NOREKLAS, TGLREKLAS, NILAI, UMEKO, KDKIB, URAITRANS, 
		KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDBRGPO, THANG
		FROM #REKLAS_KIBB
		
		/* REKLAS ASET TETAP INSERT REKLAS MASUK -- PEMILIHAN KIB TUJUAN */	
		IF (@KDTANS = '233') 
		BEGIN
			IF (@KDKIB_2 = '08')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBBDET A
								INNER JOIN #REKLAS_KIBB K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBBDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBB K
			END
			ELSE IF (@KDKIB_2 = '09')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBBDET A
								INNER JOIN #REKLAS_KIBB K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBBDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, '09' KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBB K
			END
			
			/* INSERT KIB_SPESIFIKASI */ 
			INSERT INTO ASET_KIBSPESIFIKASI(IDBRG,URUTHIST,UNITKEY,ASETKEY,TAHUN,NOREG,KDKIB,KDPEMILIK,ASALUSUL,PENGGUNA,KET,KDHAK,LUASTNH,ALAMAT,NOFIKAT,TGFIKAT,KDSATUAN,MERKTYPE,UKURAN,
			BAHAN,KDWARNA,NOPABRIK,NORANGKA,NOPOLISI,NOBPKB,NOMESIN,BERTINGKAT,BETON,LUASLT,NODOKGDG,TGDOKGDG,KONSTRUKSI,PANJANG,LEBAR,LUAS,NODOKJIJ,TGDOKJIJ,JDLPENERBIT,BKPENCIPTA,SPESIFIKASI,
			ASALDAERAH,PENCIPTA,JENIS,KDFISIK,NODOKKDP,TGDOKKDP,TGMULAI,NOKDTANAH,JUDUL)
			SELECT AK.IDBRG, @MAXURUTTRANS+2, AK.UNITKEY, K.ASETKEY2, K.TAHUN, @NOREGN, K.KDKIB_2, AK.KDPEMILIK, AK.ASALUSUL, AK.PENGGUNA, AK.KET, AK.KDHAK,AK.LUASTNH, AK.ALAMAT, AK.NOFIKAT, 
			AK.TGFIKAT, AK.KDSATUAN,AK.MERKTYPE, AK.UKURAN, AK.BAHAN, AK.KDWARNA, AK.NOPABRIK,AK.NORANGKA, AK.NOPOLISI, AK.NOBPKB, AK.NOMESIN, AK.BERTINGKAT,AK.BETON, AK.LUASLT, AK.NODOKGDG, 
			AK.TGDOKGDG, AK.KONSTRUKSI,	AK.PANJANG, AK.LEBAR, AK.LUAS, AK.NODOKJIJ, AK.TGDOKJIJ,AK.JDLPENERBIT, AK.BKPENCIPTA, AK.SPESIFIKASI, AK.ASALDAERAH,AK.PENCIPTA, AK.JENIS, AK.KDFISIK, 
			AK.NODOKKDP, AK.TGDOKKDP, AK.TGMULAI, AK.NOKDTANAH, AK.JUDUL
			FROM #REKLAS_KIBB K
			INNER JOIN ASET_KIBSPESIFIKASI AK ON AK.IDBRG = K.IDBRG AND AK.UNITKEY = K.UNITKEY AND AK.ASETKEY = K.ASETKEY
		END	
			
		/* UPDATE STATUS REKLAS */ 
		UPDATE ASET_REKLASDET
		SET NOREG2 = (CASE WHEN @KDTANS = '233' THEN @NOREGN ELSE ''END), [STATUS] = '1'
		FROM ASET_REKLASDET A
		INNER JOIN #REKLAS_KIBB R ON R.UNITKEY = A.UNITKEY AND R.NOREKLAS = A.NOREKLAS AND A.KDTANS = @KDTANS AND R.ASETKEY = A.ASETKEY AND R.TAHUN = A.TAHUN AND R.IDBRG = A.IDBRG
			
		IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#REKLAS_KIBB%')
		DROP TABLE #REKLAS_KIBB
	END
	ELSE IF (@KDKIB = '03')
	BEGIN
		/* INSERT REKLAS KELUAR */ 
		SELECT K.IDBRG, K.UNITKEY, K.ASETKEY, K.KDASET, K.TAHUN, K.NOREG, K.NOREKLAS, K.TGLREKLAS, K.NILAI, K.UMEKO, K.KDKIB, K.URAITRANS, 
		A.KDKON, A.KDKLAS, A.KDSENSUS, A.KDSTATUSASET, A.KDLOKPO, A.KDBRGPO, K.THANG, K.ASETKEY2, K.KDASET_2, K.UMEKO_2, K.KDKIB_2
		INTO #REKLAS_KIBC
		FROM #KIB_REKLAS K
		INNER JOIN ASET_KIBCDET A ON A.IDBRG = K.IDBRG AND A.URUTTRANS = @MAXURUTTRANS
		WHERE K.NOURUT = @I
			
		INSERT INTO ASET_KIBCDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
		SELECT IDBRG, @MAXURUTTRANS+1, UNITKEY, ASETKEY, TAHUN, NOREG, @KDTANS, NOREKLAS, TGLREKLAS, NILAI, UMEKO, KDKIB, URAITRANS, 
		KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDBRGPO, THANG
		FROM #REKLAS_KIBC
		
		/* REKLAS ASET TETAP INSERT REKLAS MASUK -- PEMILIHAN KIB TUJUAN */	
		IF (@KDTANS = '233') 
		BEGIN
			IF (@KDKIB_2 = '08')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBCDET A
								INNER JOIN #REKLAS_KIBC K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBCDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBC K
			END
			ELSE IF (@KDKIB_2 = '09')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBCDET A
								INNER JOIN #REKLAS_KIBC K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBCDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, '09' KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBC K
			END
			
			
			/* INSERT KIB_SPESIFIKASI */ 
			INSERT INTO ASET_KIBSPESIFIKASI(IDBRG,URUTHIST,UNITKEY,ASETKEY,TAHUN,NOREG,KDKIB,KDPEMILIK,ASALUSUL,PENGGUNA,KET,KDHAK,LUASTNH,ALAMAT,NOFIKAT,TGFIKAT,KDSATUAN,MERKTYPE,UKURAN,
			BAHAN,KDWARNA,NOPABRIK,NORANGKA,NOPOLISI,NOBPKB,NOMESIN,BERTINGKAT,BETON,LUASLT,NODOKGDG,TGDOKGDG,KONSTRUKSI,PANJANG,LEBAR,LUAS,NODOKJIJ,TGDOKJIJ,JDLPENERBIT,BKPENCIPTA,SPESIFIKASI,
			ASALDAERAH,PENCIPTA,JENIS,KDFISIK,NODOKKDP,TGDOKKDP,TGMULAI,NOKDTANAH,JUDUL)
			SELECT AK.IDBRG, @MAXURUTTRANS+2, AK.UNITKEY, K.ASETKEY2, K.TAHUN, @NOREGN, K.KDKIB_2, AK.KDPEMILIK, AK.ASALUSUL, AK.PENGGUNA, AK.KET, AK.KDHAK,AK.LUASTNH, AK.ALAMAT, AK.NOFIKAT, 
			AK.TGFIKAT, AK.KDSATUAN,AK.MERKTYPE, AK.UKURAN, AK.BAHAN, AK.KDWARNA, AK.NOPABRIK,AK.NORANGKA, AK.NOPOLISI, AK.NOBPKB, AK.NOMESIN, AK.BERTINGKAT,AK.BETON, AK.LUASLT, AK.NODOKGDG, 
			AK.TGDOKGDG, AK.KONSTRUKSI,	AK.PANJANG, AK.LEBAR, AK.LUAS, AK.NODOKJIJ, AK.TGDOKJIJ,AK.JDLPENERBIT, AK.BKPENCIPTA, AK.SPESIFIKASI, AK.ASALDAERAH,AK.PENCIPTA, AK.JENIS, AK.KDFISIK, 
			AK.NODOKKDP, AK.TGDOKKDP, AK.TGMULAI, AK.NOKDTANAH, AK.JUDUL
			FROM #REKLAS_KIBC K
			INNER JOIN ASET_KIBSPESIFIKASI AK ON AK.IDBRG = K.IDBRG AND AK.UNITKEY = K.UNITKEY AND AK.ASETKEY = K.ASETKEY
		END	
			
		/* UPDATE STATUS REKLAS */ 
		UPDATE ASET_REKLASDET
		SET NOREG2 = (CASE WHEN @KDTANS = '233' THEN @NOREGN ELSE ''END), [STATUS] = '1'
		FROM ASET_REKLASDET A
		INNER JOIN #REKLAS_KIBC R ON R.UNITKEY = A.UNITKEY AND R.NOREKLAS = A.NOREKLAS AND A.KDTANS = @KDTANS AND R.ASETKEY = A.ASETKEY AND R.TAHUN = A.TAHUN AND R.IDBRG = A.IDBRG
			
		IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#REKLAS_KIBC%')
		DROP TABLE #REKLAS_KIBC
	END
	ELSE IF (@KDKIB = '04')
	BEGIN			
		/* INSERT REKLAS KELUAR */ 
		SELECT K.IDBRG, K.UNITKEY, K.ASETKEY, K.KDASET, K.TAHUN, K.NOREG, K.NOREKLAS, K.TGLREKLAS, K.NILAI, K.UMEKO, K.KDKIB, K.URAITRANS, 
		A.KDKON, A.KDKLAS, A.KDSENSUS, A.KDSTATUSASET, A.KDLOKPO, A.KDBRGPO, K.THANG, K.ASETKEY2, K.KDASET_2, K.UMEKO_2, K.KDKIB_2
		INTO #REKLAS_KIBD
		FROM #KIB_REKLAS K
		INNER JOIN ASET_KIBDDET A ON A.IDBRG = K.IDBRG AND A.URUTTRANS = @MAXURUTTRANS
		WHERE K.NOURUT = @I
			
		INSERT INTO ASET_KIBDDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
		SELECT IDBRG, @MAXURUTTRANS+1, UNITKEY, ASETKEY, TAHUN, NOREG, @KDTANS, NOREKLAS, TGLREKLAS, NILAI, UMEKO, KDKIB, URAITRANS, 
		KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDBRGPO, THANG
		FROM #REKLAS_KIBD
		
		/* REKLAS ASET TETAP INSERT REKLAS MASUK -- PEMILIHAN KIB TUJUAN */	
		IF (@KDTANS = '233') 
		BEGIN
			IF (@KDKIB_2 = '08')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBDDET A
								INNER JOIN #REKLAS_KIBD K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBDDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBD K
			END
			ELSE IF (@KDKIB_2 = '09')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBDDET A
								INNER JOIN #REKLAS_KIBD K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBDDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, '09' KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBD K
			END
			
			
			/* INSERT KIB_SPESIFIKASI */ 
			INSERT INTO ASET_KIBSPESIFIKASI(IDBRG,URUTHIST,UNITKEY,ASETKEY,TAHUN,NOREG,KDKIB,KDPEMILIK,ASALUSUL,PENGGUNA,KET,KDHAK,LUASTNH,ALAMAT,NOFIKAT,TGFIKAT,KDSATUAN,MERKTYPE,UKURAN,
			BAHAN,KDWARNA,NOPABRIK,NORANGKA,NOPOLISI,NOBPKB,NOMESIN,BERTINGKAT,BETON,LUASLT,NODOKGDG,TGDOKGDG,KONSTRUKSI,PANJANG,LEBAR,LUAS,NODOKJIJ,TGDOKJIJ,JDLPENERBIT,BKPENCIPTA,SPESIFIKASI,
			ASALDAERAH,PENCIPTA,JENIS,KDFISIK,NODOKKDP,TGDOKKDP,TGMULAI,NOKDTANAH,JUDUL)
			SELECT AK.IDBRG, @MAXURUTTRANS+2, AK.UNITKEY, K.ASETKEY2, K.TAHUN, @NOREGN, K.KDKIB_2, AK.KDPEMILIK, AK.ASALUSUL, AK.PENGGUNA, AK.KET, AK.KDHAK,AK.LUASTNH, AK.ALAMAT, AK.NOFIKAT, 
			AK.TGFIKAT, AK.KDSATUAN,AK.MERKTYPE, AK.UKURAN, AK.BAHAN, AK.KDWARNA, AK.NOPABRIK,AK.NORANGKA, AK.NOPOLISI, AK.NOBPKB, AK.NOMESIN, AK.BERTINGKAT,AK.BETON, AK.LUASLT, AK.NODOKGDG, 
			AK.TGDOKGDG, AK.KONSTRUKSI,	AK.PANJANG, AK.LEBAR, AK.LUAS, AK.NODOKJIJ, AK.TGDOKJIJ,AK.JDLPENERBIT, AK.BKPENCIPTA, AK.SPESIFIKASI, AK.ASALDAERAH,AK.PENCIPTA, AK.JENIS, AK.KDFISIK, 
			AK.NODOKKDP, AK.TGDOKKDP, AK.TGMULAI, AK.NOKDTANAH, AK.JUDUL
			FROM #REKLAS_KIBD K
			INNER JOIN ASET_KIBSPESIFIKASI AK ON AK.IDBRG = K.IDBRG AND AK.UNITKEY = K.UNITKEY AND AK.ASETKEY = K.ASETKEY
		END	
		
		/* UPDATE STATUS REKLAS */ 
		UPDATE ASET_REKLASDET
		SET NOREG2 = (CASE WHEN @KDTANS = '233' THEN @NOREGN ELSE ''END), [STATUS] = '1'
		FROM ASET_REKLASDET A
		INNER JOIN #REKLAS_KIBD R ON R.UNITKEY = A.UNITKEY AND R.NOREKLAS = A.NOREKLAS AND A.KDTANS = @KDTANS AND R.ASETKEY = A.ASETKEY AND R.TAHUN = A.TAHUN AND R.IDBRG = A.IDBRG
			
		IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#REKLAS_KIBD%')
		DROP TABLE #REKLAS_KIBD
	END
	ELSE IF (@KDKIB = '05')
	BEGIN
		/* INSERT REKLAS KELUAR */ 
		SELECT K.IDBRG, K.UNITKEY, K.ASETKEY, K.KDASET, K.TAHUN, K.NOREG, K.NOREKLAS, K.TGLREKLAS, K.NILAI, K.UMEKO, K.KDKIB, K.URAITRANS, 
		A.KDKON, A.KDKLAS, A.KDSENSUS, A.KDSTATUSASET, A.KDLOKPO, A.KDBRGPO, K.THANG, K.ASETKEY2, K.KDASET_2, K.UMEKO_2, K.KDKIB_2
		INTO #REKLAS_KIBE
		FROM #KIB_REKLAS K
		INNER JOIN ASET_KIBEDET A ON A.IDBRG = K.IDBRG AND A.URUTTRANS = @MAXURUTTRANS
		WHERE K.NOURUT = @I
			
		INSERT INTO ASET_KIBEDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
		SELECT IDBRG, @MAXURUTTRANS+1, UNITKEY, ASETKEY, TAHUN, NOREG, @KDTANS, NOREKLAS, TGLREKLAS, NILAI, UMEKO, KDKIB, URAITRANS, 
		KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDBRGPO, THANG
		FROM #REKLAS_KIBE
		
		/* REKLAS ASET TETAP INSERT REKLAS MASUK -- PEMILIHAN KIB TUJUAN */	
		IF (@KDTANS = '233') 	
		BEGIN
			IF (@KDKIB_2 = '08')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBEDET A
								INNER JOIN #REKLAS_KIBE K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBEDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBE K
			END
			ELSE IF (@KDKIB_2 = '09')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBEDET A
								INNER JOIN #REKLAS_KIBE K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBEDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, '09' KDSTATUSASET, KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBE K
			END
			
			
			/* INSERT KIB_SPESIFIKASI */ 
			INSERT INTO ASET_KIBSPESIFIKASI(IDBRG,URUTHIST,UNITKEY,ASETKEY,TAHUN,NOREG,KDKIB,KDPEMILIK,ASALUSUL,PENGGUNA,KET,KDHAK,LUASTNH,ALAMAT,NOFIKAT,TGFIKAT,KDSATUAN,MERKTYPE,UKURAN,
			BAHAN,KDWARNA,NOPABRIK,NORANGKA,NOPOLISI,NOBPKB,NOMESIN,BERTINGKAT,BETON,LUASLT,NODOKGDG,TGDOKGDG,KONSTRUKSI,PANJANG,LEBAR,LUAS,NODOKJIJ,TGDOKJIJ,JDLPENERBIT,BKPENCIPTA,SPESIFIKASI,
			ASALDAERAH,PENCIPTA,JENIS,KDFISIK,NODOKKDP,TGDOKKDP,TGMULAI,NOKDTANAH,JUDUL)
			SELECT AK.IDBRG, @MAXURUTTRANS+2, AK.UNITKEY, K.ASETKEY2, K.TAHUN, @NOREGN, K.KDKIB_2, AK.KDPEMILIK, AK.ASALUSUL, AK.PENGGUNA, AK.KET, AK.KDHAK,AK.LUASTNH, AK.ALAMAT, AK.NOFIKAT, 
			AK.TGFIKAT, AK.KDSATUAN,AK.MERKTYPE, AK.UKURAN, AK.BAHAN, AK.KDWARNA, AK.NOPABRIK,AK.NORANGKA, AK.NOPOLISI, AK.NOBPKB, AK.NOMESIN, AK.BERTINGKAT,AK.BETON, AK.LUASLT, AK.NODOKGDG, 
			AK.TGDOKGDG, AK.KONSTRUKSI,	AK.PANJANG, AK.LEBAR, AK.LUAS, AK.NODOKJIJ, AK.TGDOKJIJ,AK.JDLPENERBIT, AK.BKPENCIPTA, AK.SPESIFIKASI, AK.ASALDAERAH,AK.PENCIPTA, AK.JENIS, AK.KDFISIK, 
			AK.NODOKKDP, AK.TGDOKKDP, AK.TGMULAI, AK.NOKDTANAH, AK.JUDUL
			FROM #REKLAS_KIBE K
			INNER JOIN ASET_KIBSPESIFIKASI AK ON AK.IDBRG = K.IDBRG AND AK.UNITKEY = K.UNITKEY AND AK.ASETKEY = K.ASETKEY
		END
			
		/* UPDATE STATUS REKLAS */ 
		UPDATE ASET_REKLASDET
		SET NOREG2 = (CASE WHEN @KDTANS = '233' THEN @NOREGN ELSE ''END), [STATUS] = '1'
		FROM ASET_REKLASDET A
		INNER JOIN #REKLAS_KIBE R ON R.UNITKEY = A.UNITKEY AND R.NOREKLAS = A.NOREKLAS AND A.KDTANS = @KDTANS AND R.ASETKEY = A.ASETKEY AND R.TAHUN = A.TAHUN AND R.IDBRG = A.IDBRG
			
		IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#REKLAS_KIBE%')
		DROP TABLE #REKLAS_KIBE
	END
	ELSE IF (@KDKIB = '07')
	BEGIN
		/* INSERT REKLAS KELUAR */ 
		SELECT K.IDBRG, K.UNITKEY, K.ASETKEY, K.KDASET, K.TAHUN, K.NOREG, K.NOREKLAS, K.TGLREKLAS, K.NILAI, K.UMEKO, K.KDKIB, K.URAITRANS, 
		A.KDKON, A.KDKLAS, A.KDSENSUS, A.KDSTATUSASET, A.KDLOKPO, A.KDBRGPO, K.THANG, K.ASETKEY2, K.KDASET_2, K.UMEKO_2, K.KDKIB_2
		INTO #REKLAS_KIBG
		FROM #KIB_REKLAS K
		INNER JOIN ASET_KIBGDET A ON A.IDBRG = K.IDBRG AND A.URUTTRANS = @MAXURUTTRANS
		WHERE K.NOURUT = @I
			
		INSERT INTO ASET_KIBGDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
		SELECT IDBRG, @MAXURUTTRANS+1, UNITKEY, ASETKEY, TAHUN, NOREG, @KDTANS, NOREKLAS, TGLREKLAS, NILAI, UMEKO, KDKIB, URAITRANS, 
		KDKON, KDKLAS, KDSENSUS, KDSTATUSASET, KDLOKPO, KDBRGPO, THANG
		FROM #REKLAS_KIBG
		
		/* REKLAS ASET TETAP INSERT REKLAS MASUK -- PEMILIHAN KIB TUJUAN */	
		IF (@KDTANS = '233') 	
		BEGIN
			IF (@KDKIB_2 = '08')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBGDET A
								INNER JOIN #REKLAS_KIBG K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBGDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				KDKON, KDKLAS, KDSENSUS, '02', KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBG K
			END
			ELSE IF (@KDKIB_2 = '09')
			BEGIN
				SET @NOREGN	= (SELECT dbo.fn_GetNoreg(ISNULL(MAX(CAST(A.NOREG AS INT)),0)+1) 
								FROM ASET_KIBGDET A
								INNER JOIN #REKLAS_KIBG K ON A.UNITKEY = K.UNITKEY AND A.ASETKEY = K.ASETKEY2 AND A.TAHUN = K.TAHUN)
						       
				INSERT INTO ASET_KIBGDET(IDBRG,URUTTRANS,UNITKEY,ASETKEY,TAHUN,NOREG,KDTANS,NODOKUMEN,TGLDOKUMEN,NILAI,UMEKO,KDKIB,KET,KDKON,KDKLAS,KDSENSUS,KDSTATUSASET,KDLOKPO,KDBRGPO,THANG)
				SELECT IDBRG, @MAXURUTTRANS+2, UNITKEY, ASETKEY2, TAHUN, @NOREGN, '308', NOREKLAS, TGLREKLAS, NILAI, UMEKO_2, KDKIB_2, URAITRANS, 
				'05' KDKON, KDKLAS, KDSENSUS, '02', KDLOKPO, KDKIB_2+'.'+LTRIM(RTRIM(KDASET_2))+@NOREGN, THANG
				FROM #REKLAS_KIBG K
			END
			
			/* INSERT KIB_SPESIFIKASI */ 
			INSERT INTO ASET_KIBSPESIFIKASI(IDBRG,URUTHIST,UNITKEY,ASETKEY,TAHUN,NOREG,KDKIB,KDPEMILIK,ASALUSUL,PENGGUNA,KET,KDHAK,LUASTNH,ALAMAT,NOFIKAT,TGFIKAT,KDSATUAN,MERKTYPE,UKURAN,
			BAHAN,KDWARNA,NOPABRIK,NORANGKA,NOPOLISI,NOBPKB,NOMESIN,BERTINGKAT,BETON,LUASLT,NODOKGDG,TGDOKGDG,KONSTRUKSI,PANJANG,LEBAR,LUAS,NODOKJIJ,TGDOKJIJ,JDLPENERBIT,BKPENCIPTA,SPESIFIKASI,
			ASALDAERAH,PENCIPTA,JENIS,KDFISIK,NODOKKDP,TGDOKKDP,TGMULAI,NOKDTANAH,JUDUL)
			SELECT AK.IDBRG, @MAXURUTTRANS+2, AK.UNITKEY, K.ASETKEY2, K.TAHUN, @NOREGN, K.KDKIB_2, AK.KDPEMILIK, AK.ASALUSUL, AK.PENGGUNA, AK.KET, AK.KDHAK,AK.LUASTNH, AK.ALAMAT, AK.NOFIKAT, 
			AK.TGFIKAT, AK.KDSATUAN,AK.MERKTYPE, AK.UKURAN, AK.BAHAN, AK.KDWARNA, AK.NOPABRIK,AK.NORANGKA, AK.NOPOLISI, AK.NOBPKB, AK.NOMESIN, AK.BERTINGKAT,AK.BETON, AK.LUASLT, AK.NODOKGDG, 
			AK.TGDOKGDG, AK.KONSTRUKSI,	AK.PANJANG, AK.LEBAR, AK.LUAS, AK.NODOKJIJ, AK.TGDOKJIJ,AK.JDLPENERBIT, AK.BKPENCIPTA, AK.SPESIFIKASI, AK.ASALDAERAH,AK.PENCIPTA, AK.JENIS, AK.KDFISIK, 
			AK.NODOKKDP, AK.TGDOKKDP, AK.TGMULAI, AK.NOKDTANAH, AK.JUDUL
			FROM #REKLAS_KIBG K
			INNER JOIN ASET_KIBSPESIFIKASI AK ON AK.IDBRG = K.IDBRG AND AK.UNITKEY = K.UNITKEY AND AK.ASETKEY = K.ASETKEY
		END	
			
		/* UPDATE STATUS REKLAS */ 
		UPDATE ASET_REKLASDET
		SET NOREG2 = (CASE WHEN @KDTANS = '233' THEN @NOREGN ELSE ''END), [STATUS] = '1'
		FROM ASET_REKLASDET A
		INNER JOIN #REKLAS_KIBG R ON R.UNITKEY = A.UNITKEY AND R.NOREKLAS = A.NOREKLAS AND A.KDTANS = @KDTANS AND R.ASETKEY = A.ASETKEY AND R.TAHUN = A.TAHUN AND R.IDBRG = A.IDBRG
			
		IF EXISTS (SELECT NAME FROM TEMPDB..SYSOBJECTS  WHERE NAME LIKE '#REKLAS_KIBG%')
		DROP TABLE #REKLAS_KIBG
	END
		
	SET @I = @I + 1
END

COMMIT TRANSACTION

-- UPDATE TGLVALID
UPDATE ASET_REKLAS
SET TGLVALID = @TGLREKLAS
WHERE UNITKEY=@UNITKEY AND NOREKLAS=@NOREKLAS AND KDTANS=@KDTANS
GO


