//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("", ClrNamespace="")]

namespace CoreNET.Common.Services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CoreNET.Common.Services")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Daftunits", Namespace="http://schemas.datacontract.org/2004/07/CoreNET.Common.Services", ItemName="Daftunit")]
    public class Daftunits : System.Collections.Generic.List<Daftunit>
    {
    }
}


[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Name="Daftunit", Namespace="")]
public partial class Daftunit : object, System.Runtime.Serialization.IExtensibleDataObject
{
    
    private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
    
    private string KdunitField;
    
    private string NmunitField;
    
    public System.Runtime.Serialization.ExtensionDataObject ExtensionData
    {
        get
        {
            return this.extensionDataField;
        }
        set
        {
            this.extensionDataField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Kdunit
    {
        get
        {
            return this.KdunitField;
        }
        set
        {
            this.KdunitField = value;
        }
    }
    
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Nmunit
    {
        get
        {
            return this.NmunitField;
        }
        set
        {
            this.NmunitField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceDataControl")]
public interface IServiceDataControl
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataControl/GetData", ReplyAction="http://tempuri.org/IServiceDataControl/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataControl/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceDataControl/GetDataUsingDataContractResponse")]
    CoreNET.Common.Services.CompositeType GetDataUsingDataContract(CoreNET.Common.Services.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDataControl/GetList", ReplyAction="http://tempuri.org/IServiceDataControl/GetListResponse")]
    CoreNET.Common.Services.Daftunits GetList(int mode);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceDataControlChannel : IServiceDataControl, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceDataControlClient : System.ServiceModel.ClientBase<IServiceDataControl>, IServiceDataControl
{
    
    public ServiceDataControlClient()
    {
    }
    
    public ServiceDataControlClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceDataControlClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceDataControlClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceDataControlClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public CoreNET.Common.Services.CompositeType GetDataUsingDataContract(CoreNET.Common.Services.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public CoreNET.Common.Services.Daftunits GetList(int mode)
    {
        return base.Channel.GetList(mode);
    }
}
